### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by arquio** [APIs-guru/graphql-faker#53]
Hello, 

I have this problem:

![graphql-faker_2018-08-23 17-01-26](https://user-images.githubusercontent.com/414590/44533554-0f14ff00-a6f6-11e8-92b3-06263ddf6da6.png)

``` bash
PayloadTooLargeError: request entity too large
    at readStream (/home/user/.config/yarn/global/node_modules/raw-body/index.js:155:17)
    at getRawBody (/home/user/.config/yarn/global/node_modules/raw-body/index.js:108:12)
    at read (/home/user/.config/yarn/global/node_modules/body-parser/lib/read.js:77:3)
    at textParser (/home/user/.config/yarn/global/node_modules/body-parser/lib/types/text.js:86:5)
    at Layer.handle [as handle_request] (/home/user/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/.config/yarn/global/node_modules/express/lib/router/index.js:317:13)
    at /home/user/.config/yarn/global/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/user/.config/yarn/global/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user/.config/yarn/global/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/user/.config/yarn/global/node_modules/express/lib/middleware/init.js:40:5)
```
version: 1.7.0 and 1.7.5
filesize 4100 lines /108K

Someone have any idea what could have happened or how can I fix it?

Thanks!!

**Comment by OoXoSoO** [comment]
I have the same problem too
